# Generated by Django 5.2.1 on 2025-05-30 10:09

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('clothes', 'clothes'), ('toys', 'toys'), ('books', 'books'), ('games', 'games'), ('cars', 'cars'), ('home', 'home'), ('other', 'other')], default='other', max_length=50)),
                ('condition', models.CharField(choices=[('new', 'new'), ('used', 'used')], default='used', max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('traded', 'traded'), ('archived', 'archived')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'db_table': 'ad',
                'ordering': ['-created_at'],
            },
        ),
    ]
